###
### Stage 0: Build NCEP libraries
###

FROM  intel/oneapi-hpckit:devel-ubuntu18.04 AS ncep-bld 

RUN apt-get update && apt-get install -y git && \
    git config --global http.sslverify false && \
    git clone https://github.com/NCAR/NCEPlibs.git && \
    cd NCEPlibs && \
    git checkout 3da51e139d5cd731c9fc27f39d88cb4e1328212b && \
    mkdir -p /myapps/ncep/lib && \
    export PATH=/usr/bin:$PATH && \
    echo "y" | ./make_ncep_libs.sh -s linux-c intel -d /myapps/ncep -o 1 && \ 
    mv *.a /myapps/ncep/lib && cd .. && rm -rf NCEPlibs

###
### Stage 1: Build zlib, HDF5 and NetCDF libraries 
###

FROM intel/oneapi-hpckit:devel-ubuntu18.04 AS io-bld

RUN apt-get update && \
    apt-get install -y make autoconf libtool m4 git wget

RUN wget -q https://zlib.net/zlib-1.2.11.tar.gz && \
    mkdir -p /myapps/zlib && \
    tar xzf zlib-1.2.11.tar.gz && cd zlib-1.2.11 && \
    CC=icc ./configure --prefix=/myapps/zlib && \
    make -j8 && make install && \
    cd .. && rm -rf zlib*

RUN git clone -b hdf5_1_10_7 https://bitbucket.hdfgroup.org/scm/hdffv/hdf5.git && \
    mkdir -p /myapps/hdf5 && \
    cd hdf5 && \
    autoreconf -i && \
    CC=icc FC=ifort CXX=icpc ./configure --with-zlib=/myapps/zlib --enable-build-mode=production --disable-tests --disable-tools --enable-fortran --prefix=/myapps/hdf5 && \
    make -j 24 && make install && \
    cd .. && rm -rf hdf5*

RUN wget -q https://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-c-4.7.4.tar.gz && \
    tar xzf netcdf-c-4.7.4.tar.gz && \
    mkdir -p /myapps/netcdf && \
    cd netcdf-c-4.7.4 && \
    export LD_LIBRARY_PATH=/myapps/zlib/lib:/myapps/hdf5/lib:$LD_LIBRARY_PATH && \
    CC=icc CXX=icpc CPPFLAGS="-I/myapps/zlib/include -I/myapps/hdf5/include" LDFLAGS="-L/myapps/zlib/lib -L/myapps/hdf5/lib" ./configure --prefix=/myapps/netcdf --disable-dap --disable-testsets --disable-utilities && \
    make -j 24 && make install && \
    cd .. && rm -rf netcdf-c*

RUN wget -q https://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-fortran-4.5.3.tar.gz && \
    mkdir -p /myapps/netcdf-fortran && \
    tar xzf netcdf-fortran-4.5.3.tar.gz && \ 
    cd netcdf-fortran-4.5.3 && \
    export LD_LIBRARY_PATH=/myapps/zlib/lib:/myapps/hdf5/lib:/myapps/netcdf/lib:${LD_LIBRARY_PATH} && \
    CC=icc FC=ifort F77=ifort CPPFLAGS="-I/myapps/zlib/include -I/myapps/hdf5/include -I/myapps/netcdf/include" LDFLAGS="-L/myapps/zlib/lib -L/myapps/hdf5/lib -L/myapps/netcdf/lib" ./configure --prefix=/myapps/netcdf && \    
    make -j 24 && make install && \
    cd .. && rm -rf netcdf*

###
### Stage 2: Build ESMF library and modules
###

FROM intel/oneapi-hpckit:devel-ubuntu18.04 AS esmf-bld

COPY --from=io-bld /myapps/hdf5/ /myapps/hdf5/
COPY --from=io-bld /myapps/netcdf/ /myapps/netcdf/

RUN export ESMF_DIR=/esmf ESMF_INSTALL_PREFIX=/myapps/esmf ESMF_COMM=intelmpi ESMF_LAPACK=mkl && \
    export ESMF_NETCDF_INCLUDE=/myapps/netcdf/include && ESMF_NETCDF_LIBS="-L/myapps/netcdf/lib -lnetcdf -lnetcdff" ESMF_BOPT=O3 && \
    git clone -b ESMF_8_0_0 --depth 1 https://git.code.sf.net/p/esmf/esmf && \
    export PATH=/usr/bin:$PATH && \
    cd esmf && make -j8 lib 
 
RUN mkdir -p /myapps/esmf/include && mkdir -p /myapps/esmf/lib && \
    cd /esmf/lib/libO/Linux.intel.64.intelmpi.default && \
    cp *.so /myapps/esmf/lib/ && cp *.a /myapps/esmf/lib/ && cp esmf.mk /myapps/esmf/lib/ && \
    cd /esmf/mod/modO/Linux.intel.64.intelmpi.default && \
    cp *.mod /myapps/esmf/include/ && \
    cd /esmf/src/include && \ 
    cp *.h /myapps/esmf/include/

###
### Stage 3: Build the FMS library and modules
###

FROM mpich-bld AS fms-bld

COPY --from=io-bld /myapps/hdf5/ /myapps/hdf5/
COPY --from=io-bld /myapps/netcdf/ /myapps/netcdf/

RUN apt-get update && \
    apt-get install -y git autoconf libtool m4 bats 

RUN git clone https://github.com/VulcanClimateModeling/fv3gfs-fortran.git && \
    mkdir -p /myapps/fms && \
    cd fv3gfs-fortran/FMS && \
    export CC=mpiicc FC=mpiifort LDFLAGS="-L/usr/lib -L/myapps/netcdf/lib -L/myapps/hdf5/lib -L/opt/intel/oneapi/mkl/latest/lib/intel64" && \
    export LOG_DRIVER_FLAGS="--comments" && \
    export CPPFLAGS="-I/myapps/netcdf/include -I/myapps/hdf5/include -I/opt/intel/oneapi/mkl/latest/include -Duse_LARGEFILE -DMAXFIELDMETHODS_=500 -DGFS_PHYS" && \ 
    export FCFLAGS="-fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -nowarn -sox -align array64byte -i4 -real-size 64 -no-prec-div -no-prec-sqrt -qopenmp" && \
    autoreconf -i && \ 
    ./configure --prefix=/myapps/fms && \
    make && make install 

###
### Stage 4: Compile FV3
###

FROM esmf-bld AS fv3-bld 

COPY --from=io-bld /myapps/hdf5/ /myapps/hdf5/
COPY --from=io-bld /myapps/netcdf/ /myapps/netcdf/
COPY --from=fms-bld /myapps/fms/ /myapps/fms/
COPY --from=ncep-bld /myapps/ncep/ /myapps/ncep/

RUN git clone https://github.com/VulcanClimateModeling/fv3gfs-fortran.git && \
    cd fv3gfs-fortran/FV3 && \
    cp conf/configure.fv3.linux_intel conf/configure.fv3 && \
    export MPI_CC=mpiicc MPI_F90=mpiifort && \
    export FMS_DIR=/myapps/fms ESMF_DIR=/myapps/esmf ESMF_INC="-I/myapps/esmf/include" NCEPLIBS_DIR=/myapps/ncep NETCDF_DIR=/myapps/netcdf && \
    make clean_no_dycore && make libs_no_dycore -j8 && \
    cd atmos_cubed_sphere && make clean && \
    cd .. && make -j8 && \
    mkdir -p /myapps/fv3 && cp fv3.exe /myapps/fv3 && \
    cd ../.. && rm -rf fv3gfs-fortran

ENV LD_LIBRARY_PATH=/myapps/esmf/lib:/myapps/fms/lib:$LD_LIBRARY_PATH
ENV OMP_NUM_THREADS=1 
