#!/bin/bash -l
#SBATCH --job-name="FV3gfs_200km_resolution"
#SBATCH --partition=cscsci
#SBATCH --constraint=gpu
#SBATCH --account=d107
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks=6
#SBATCH --hint=nomultithread

##
## Set the compute node environment
##

module load daint-gpu
module load sarus

export OMP_NUM_THREADS=1
ulimit -s unlimited

srun sarus run --mpi --mount=type=bind,source=${SCRATCH_DIR},destination=/scratch --workdir=/scratch load/library/${FV3_CONTAINER} /myapps/fv3/fv3.exe
