#!/bin/bash -l
#SBATCH --job-name="FV3gfs_800km_resolution"
#SBATCH --partition=cscsci
#SBATCH --constraint=gpu
#SBATCH --time=00:04:00
#SBATCH --nodes=1
#SBATCH --ntasks=6
#SBATCH --hint=nomultithread

##
## Set the compute node environment
##

module load daint-gpu sarus

export OMP_NUM_THREADS=1
ulimit -s unlimited

##
## Perform the c12 test
##

srun sarus run --mpi --mount=type=bind,source=${SCRATCH_DIR},destination=/scratch --workdir=/scratch load/library/${FV3_CONTAINER} /myapps/fv3/fv3.exe
